export const translate = {
  en: {
    dashboard: "Dashboard",
    parcels: "Parcels",
    tasks: "Tasks",
    yields: "Yields",
    crops: "Crops",
    help: "Help",
    logout: "Sign out",
    slogan: "Nurture data, harvest impact",
    activeparcels: "Active parcels",
    completedtasks: "Completed tasks",
    totalyield: "Total yield",
    averageyield: "Average yield",
    zoomonparcel: "Zoom on Parcel",
    search: "Search on parcel...",
    titleanalytics: "Analytics",
    charttitleyield: "Yield Evolution",
    parcelanalytics: "Parcels Analytics",
    parcel: "Parcel",
    sortby: "Sort by",
    sortname: "Name (A → Z)",
    sortyield: "Yield (desc)",
    meanyield: "Mean Yield",
    meanyieldperarea: "Mean Yield per Area",
    yieldperarea: "Yield per Area",
    titleparcellist: "Parcels List",
    rowperpage: "Rows per page:",
    filterbyowner: "Filter by Owner",
    filterbyparcel: "Filter by Parcel",
    export: "Export",
    addparcel: "Add Parcel",
    thparcelname: "Parcel",
    thlatitude: "Latitude",
    thlongitude: "Longitude",
    thactions: "Actions",
    prev: "Prev",
    next: "Next",
    noparcelsfound: "No Parcels found.",
    instructions: "Instructions",
    step1:
      "First, use the <span class='font-semibold'>search bar</span> to locate your field.",
    step2:
      "Click on the <span class='font-semibold'>map</span> to add points and draw your parcel.",
    step3:
      "A minimum of <span class='font-semibold'>3 points</span> is required to create a polygon.",
    step4:
      "Enter a <span class='font-semibold'>parcel name</span> in the form.",
    step5:
      "Finally, click <span class='font-semibold text-[#f4a261]'>Save parcel</span> to validate.",
    titlesaveparcel: "Save Parcel",
    searchintruction: "Click on the map to draw your polygon.",
    searchonmap: "Search on map",
    parcelarea: "Parcel Area",
    btnsaveparcel: "Save parcel",
    parceldetail: "Parcel Details",
    owner: "Owner",
    area: "Area",
    croptype: "Crop Type",
    charttitleweather: "Weather Condition",
    chartprecipitation: "Precipitation",
    soilinfo: "Soil Info",
    titletaskperform: "Tasks to Perform",
    seeall: "See All",
    addtask: "Add Task",
    charttitletask: "Tasks evolution",
    harvesthistory: "Harvest History",
    thdate: "Date",
    thyield: "Yield (kg)",
    thobservation: "Observation",
    thtendance: "Trend",
    edit: "Edit",
    show: "Show",
    nohistoryfound: "No records found.",
    priorityLow: "Low",
    priorityMedium: "Medium",
    priorityHigh: "High",
    priority: "Priority",
    due: "Due",
    statusPending: "Pending",
    statusInProgress: "In Progress",
    statusDone: "Done",
    statusCancelled: "Cancelled",
    chartTasksByStatus: "Tasks by Status",
    chartYieldEvolution: "Yield (kg)",
    chartTemperature: "Temperature (°C)",
    chartPrecipitation: "Precipitation (mm/day)",
    titleeditparcel: "Edit parcel",
    titiletaskslist: "Tasks List",
    history: "History",
    upcoming: "Upcoming",
    btnaddtask: "Add task",
    taskname: "Task",
    parcelcrop: "Parcel Crop",
    status: "Status",
    notaskfound: "No tasks found.",
    titlenewtask: "New task",
    desc: "Description",
    detailtask: "Task Details",
    createdat: "Created At",
    updatedat: "Updated At",
    completedat: "Completed At",
    back: "Back",
    edittask: "Edit Task",
    savetask: "Save Task",
    yieldlist: "Yield Records",
    btnyield: "Add Yield",
    crop: "Crop",
    noyieldfound: "No yield records found.",
    newyield: "New Yield",
    notes: "Notes",
    yielddetail: "Yield Detail",
    edityield: "Edit Yield",
    btnsaveyield: "Save Yield",
    parcelcroplist: "Parcel Crops List",
    btnaddparcelcrop: "Add Parcel Crop",
    plantingdate: "Planting Date",
    harvestdate: "Harvest Date",
    noparcelcropfound: "No parcel crops found.",
    newparcelcrop: "New Parcel Crop",
    btnaddcrop: "Add Crop",
    btnsaveparcelcrop: "Save Parcel Crop",
    titleyieldforcast: "Yield Forecast",
    forecastdate: "Forecast Date",
    pareclcropdetail: "Parcel Crop Details",
    editparcelcrop: "Edit Parcel Crop",
    newcrop: "New crop",
    cropname: "Crop Name",
    variety: "Variety",
    btnsavecrop: "Save Crop",
    heroTitle:
      "I'm Sesily, your Agronomist Assistant. <br/>Ask me your farming questions!",
    ask: "Ask a question",
    suggestedQuestions: [
      "What is the best fertilizer for rice?",
      "How do I prevent maize pests?",
      "When should I plant cassava?",
      "What is the right spacing for tomato plants?",
      "How can I improve soil fertility?",
    ],
    welcomeMessage:
      "I’m **Sesile**, your Agronomist Assistant. Ask me your farming questions!",
    helpcenter: "SmartSaha – Help Center",
    welcomehelp: "Welcome to SmartSaha Guide",
    introhelp:
      "SmartSaha is a Precision Agriculture platform designed to help farmers plan, monitor, and optimize their crops using reliable data and intelligent analytics.",
    learnmore: "Learn more at",
    howitworks: "How SmartSaha Works",
    step1title: "Sign Up & Setup",
    step1text:
      "Create an account and register your farm plots to start receiving personalized recommendations.",
    step2title: "Data Collection",
    step2text:
      "Weather, soil, and crop data are collected through sensors, satellites, and field surveys.",
    step3title: "Smart Analysis",
    step3text:
      "Our system analyzes the data to determine the precise needs of each plot: irrigation, fertilization, and crop protection.",
    step4title: "Recommendations & Action Plan",
    step4text:
      "Receive tailored recommendations along with a detailed work plan for each plot.",
    step5title: "Monitoring & Optimization",
    step5text:
      "Track crop progress in real time and adjust actions to maximize yield and sustainability.",
    step6title: "Reports & Decision Making",
    step6text:
      "Get comprehensive reports to make informed decisions and improve overall farm performance.",
    needhelp: "Need Further Assistance?",
    contactteam: "Reach out to our support team:",
    location: "Antananarivo, Madagascar",
    cropStatusPlanned: "Planned",
    cropStatusPlanted: "Planted",
    cropStatusGerminated: "Germinated",
    cropStatusGrowing: "Growing",
    cropStatusFlowering: "Flowering",
    cropStatusFruiting: "Fruiting",
    cropStatusMature: "Mature",
    cropStatusHarvested: "Harvested",
    cropStatusPostHarvest: "Post-Harvest",
    cropStatusFailed: "Failed",
    points: "Added Points",
    nopoinntsfound: "No points selected on the map",
    policy: "Privacy Policy",
    policyDate: "Last Updated: September 30, 2025",
    policy1Title: "1. Introduction",
    policy1Text:
      "SmartSaha is committed to protecting your privacy and personal data. This policy explains how we collect, use, store, and protect your information in accordance with Malagasy law.",
    policy2Title: "2. Data We Collect",
    policy2Text: `
      <li><strong>Identification Data:</strong> Name, phone number, email, farm location.</li>
      <li><strong>Agricultural Data:</strong> Crop type, parcel size, yield history, soil data.</li>
      <li><strong>Technical Data:</strong> Login info, device details, IP address, browsing data.</li>
      <li><strong>Geospatial Data:</strong> GPS coordinates, satellite imagery.</li>
    `,
    policy3Title: "3. Use of Your Data",
    policy3Text: `
      <li>Service delivery and personalized recommendations.</li>
      <li>Platform optimization and analytics.</li>
      <li>Notifications, alerts, and agronomic communications.</li>
      <li>Partner connections (with your consent).</li>
      <li>Legal and regulatory compliance.</li>
    `,
    policy4Title: "4. Data Sharing",
    policy4Text:
      "We do not sell your data. Sharing may occur with technical providers, anonymized research partners, legal authorities, or commercial partners only with your explicit consent.",
    policy5Title: "5. Data Security",
    policy5Text:
      "We apply industry-standard technical and organizational measures to ensure data protection.",
    policy6Title: "6. Your Rights",
    policy6Text:
      "You may access, update, or request deletion of your data at any time. Contact us at contact@smart-saha.com.",
    policy7Text: "SmartSaha, Antananarivo, Madagascar",
    terms: "Terms of Service",
    termsDate: "Last Updated: September 30, 2025",
    terms1Title: "1. Preamble",
    terms1Text:
      "These Terms of Service govern the use of SmartSaha. Accessing or using the platform implies full acceptance of these terms.",
    terms2Title: "2. Description of Services",
    terms2Text:
      "SmartSaha provides digital tools for farmers including precision agriculture services, forecasts, management features, and an MRV system.",
    terms3Title: "3. Account Creation & Responsibility",
    terms3Text:
      "Users must provide accurate information and maintain confidentiality of their account credentials.",
    terms4Title: "4. User Obligations",
    terms4Text: `
      <li>Use the platform responsibly and legally.</li>
      <li>Provide accurate agricultural information.</li>
      <li>Refrain from fraudulent or unlawful activities.</li>
    `,
    terms5Title: "5. Intellectual Property",
    terms5Text:
      "SmartSaha owns all platform content. Users retain ownership of their data but grant SmartSaha usage rights necessary for service delivery.",
    terms6Title: "6. Limitation of Liability",
    terms6Text:
      "Recommendations are for decision support only. SmartSaha is not liable for agricultural losses. Liability is limited to reasonable diligence.",
    terms7Title: "7. Governing Law",
    terms7Text:
      "These Terms are governed by Malagasy law. Disputes fall under the jurisdiction of Antananarivo courts, after attempts at amicable resolution.",
    profileTitle: "My Profile",
    username: "Username",
    email: "Email",
    firstName: "First Name",
    lastName: "Last Name",
    editProfile: "Edit Profile",
    account: "Account",
    signOut: "Sign Out",
    home: "Insights",
    add: "Add",
    changePasswordTitle: "Change Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    savePassword: "Save Password",
    passwordUpdated: "Password updated successfully",
    updateFailed: "Failed to update password",
    fillAllFields: "Please fill in all fields",
    saveChanges: "Save Changes",
    changePassword: "Change Password",
    sesily: "Hi! I'm Sesily",
    prevision: "Weather forecast",
    today: "Today",
    humidity: "Humidity",
    pluie: "Rain",
    vent: "Wind",
    forecastInfo: "Forecast Info",
    riskLevel: "Risk Level",
    locations: "Location",
    forecastPeriod: "Forecast Period",
    point: "Point",
    sun: "Sun",
    mon: "Mon",
    tue: "Tue",
    wed: "Wed",
    thu: "Thu",
    fri: "Fri",
    sat: "Sat",

    january: "January",
    february: "February",
    march: "March",
    april: "April",
    may: "May",
    june: "June",
    july: "July",
    august: "August",
    september: "September",
    october: "October",
    november: "November",
    december: "December",

    tasks_for: "Tasks for",
    weekday_0: "Sunday",
    weekday_1: "Monday",
    weekday_2: "Tuesday",
    weekday_3: "Wednesday",
    weekday_4: "Thursday",
    weekday_5: "Friday",
    weekday_6: "Saturday",
    month_0: "January",
    month_1: "February",
    month_2: "March",
    month_3: "April",
    month_4: "May",
    month_5: "June",
    month_6: "July",
    month_7: "August",
    month_8: "September",
    month_9: "October",
    month_10: "November",
    month_11: "December",
    totalTask: "Total Tasks",
    taskByPriority: "Tasks by Priority",
    taskProgression: "Task Progression",
    deleteParcel: "Delete Parcel",
    textConfirmDeleteParcel:
      "Are you sure you want to delete this parcel? This action cannot be undone.",
    yes: "Yes",
    no: "No",
    precipitation: "Precipitation",
    uvIndex: "UV Index",
    pointsParcel: "Parcel Points",
    markDone: "Mark Done",
    analyseMeteo: "Agricultural and Weather Analysis",
    temp: "Temperature",
    alertAgricole: "Agricultural Alert",
    irrigationRecommander: "Irrigation Recommendation",
    analyseRisk: "Risk Analysis",
    condition: "Current Condition",
    resetMdpTittle: "Reset Password",
    resetText:
      "Enter the email address associated with your account. We will send you a link to create a new password.",
    resetEmail: "Email Address",
    resetBtn: "Send Reset Link",
    resetLabel: "Please enter a valid email address.",
    errorMessage: "Link sent, please check your email inbox",
    return: "Return to Sign In",
    responseMessage:
      "If the email exists in our system, you will receive a message containing a reset link. The link may take a few minutes to arrive.",
    skip: "Skip",
    step: "Step",
    stepTittle: "Setup Wizard",
    allParcel: "All Parcels",
    exportChart: "Export Chart",
    cumulativeYield: "Cumulative Yield",
    volatility: "Volatility (Std Dev)",
    yieldRelative: "Yield Relative %",
    anomalies: "Anomalies Detected",
    selectParcel: "Select a Parcel",
    fertility: "Most Fertile Soil",
    productivity: "Most Productive Crop",
    total: "Total",
    tempAverage: "Average Temperature",
    riskParcel: "Risk Parcel",
    alerts: "Alerts",
    bestRendement: "Best Yield",
    moyenne: "Average",
    cultureSansDonnees: "Crops without data",
    culture: "Crop",
  },
  fr: {
    dashboard: "Tableau",
    parcels: "Parcelles",
    tasks: "Tâches",
    yields: "Rendements",
    crops: "Cultures",
    help: "Aide",
    logout: "Quitter",
    slogan: "Données nourries, impact récolté",
    activeparcels: "Parcelles actives",
    completedtasks: "Tâches Terminées",
    totalyield: "Total Rendements",
    averageyield: "Moyenne",
    zoomonparcel: "Zoom parcelle",
    search: "Rechercher...",
    titleanalytics: "Analyse",
    charttitleyield: "Évolution",
    parcelanalytics: "Analyse parcelles",
    parcel: "Parcelle",
    sortby: "Trier",
    sortname: "Nom (A → Z)",
    sortyield: "Rendement ↓",
    meanyield: "Moyenne",
    meanyieldperarea: "Moyenne/Surface",
    yieldperarea: "Rend./Surface",
    titleparcellist: "Parcelles",
    rowperpage: "Lignes/page :",
    filterbyowner: "Par propriétaire",
    filterbyparcel: "Par parcelle",
    export: "Exporter",
    addparcel: "Ajouter",
    thparcelname: "Parcelle",
    thlatitude: "Latitude",
    thlongitude: "Longitude",
    thactions: "Actions",
    prev: "Préc.",
    next: "Suiv.",
    noparcelsfound: "Aucune parcelle",
    instructions: "Instructions",
    step1:
      "D’abord, utilisez la <span class='font-semibold'>barre de recherche</span> pour localiser votre champ.",
    step2:
      "Cliquez sur la <span class='font-semibold'>carte</span> pour ajouter des points et tracer votre parcelle.",
    step3:
      "Un minimum de <span class='font-semibold'>3 points</span> est requis pour créer un polygone.",
    step4:
      "Saisissez un <span class='font-semibold'>nom de parcelle</span> dans le formulaire.",
    step5:
      "Enfin, cliquez sur <span class='font-semibold text-[#f4a261]'>Enregistrer la parcelle</span> pour valider.",
    titlesaveparcel: "Enregistrer la parcelle",
    searchintruction: "Cliquez sur la carte pour tracer votre polygone.",
    searchonmap: "Rechercher sur la carte",
    parcelarea: "Surface de la parcelle",
    btnsaveparcel: "Enregistrer la parcelle",
    parceldetail: "Détails Parcelle",
    owner: "Propriétaire",
    area: "Surface",
    croptype: "Type de culture",
    charttitleweather: "Conditions météo",
    chartprecipitation: "Précipitations",
    soilinfo: "Infos sol",
    titletaskperform: "Tâches à effectuer",
    seeall: "Tout voir",
    addtask: "Ajouter tâche",
    charttitletask: "Évolution des tâches",
    harvesthistory: "Historique récoltes",
    thdate: "Date",
    thyield: "Rendement (kg)",
    thobservation: "Observation",
    thtendance: "Tendance",
    edit: "Modifier",
    show: "Voir",
    nohistoryfound: "Aucun enregistrement",
    priorityLow: "Faible",
    priorityMedium: "Moyenne",
    priorityHigh: "Haute",
    priority: "Priorité",
    due: "Échéance",
    statusPending: "En attente",
    statusInProgress: "En cours",
    statusDone: "Terminée",
    statusCancelled: "Annulée",
    chartTasksByStatus: "Tâches par statut",
    chartYieldEvolution: "Rendement (kg)",
    chartTemperature: "Température (°C)",
    chartPrecipitation: "Précipitations (mm/jour)",
    titleeditparcel: "Modifier la parcelle",
    titiletaskslist: "Liste des tâches",
    history: "Historique",
    upcoming: "À venir",
    btnaddtask: "Ajouter tâche",
    taskname: "Tâche",
    parcelcrop: "Culture parcelle",
    status: "Statut",
    notaskfound: "Aucune tâche trouvée",
    titlenewtask: "Nouvelle tâche",
    desc: "Description",
    detailtask: "Détails de la tâche",
    createdat: "Créée le",
    updatedat: "Mise à jour le",
    completedat: "Terminée le",
    back: "Retour",
    edittask: "Modifier la tâche",
    savetask: "Enregistrer la tâche",
    yieldlist: "Rendements",
    btnyield: "Ajouter rendement",
    crop: "Culture",
    noyieldfound: "Aucun rendement trouvé",
    newyield: "Nouveau rendement",
    notes: "Notes",
    yielddetail: "Détails du rendement",
    edityield: "Modifier le rendement",
    btnsaveyield: "Enregistrer rendement",
    parcelcroplist: "Cultures de la parcelle",
    btnaddparcelcrop: "Ajouter culture",
    plantingdate: "Date de plantation",
    harvestdate: "Date de récolte",
    noparcelcropfound: "Aucune culture trouvée",
    newparcelcrop: "Nouvelle culture",
    btnaddcrop: "Ajouter culture",
    btnsaveparcelcrop: "Enregistrer culture",
    titleyieldforcast: "Prévision de rendement",
    forecastdate: "Date de prévision",
    pareclcropdetail: "Détails culture parcelle",
    editparcelcrop: "Modifier culture",
    newcrop: "Nouvelle culture",
    cropname: "Nom de la culture",
    variety: "Variété",
    btnsavecrop: "Enregistrer culture",
    heroTitle:
      "Je suis Sesily, votre assistante agronome. <br/>Posez-moi vos questions agricoles !",
    ask: "Poser une question",
    suggestedQuestions: [
      "Quel est le meilleur engrais pour le riz ?",
      "Comment prévenir les ravageurs du maïs ?",
      "Quand faut-il planter le manioc ?",
      "Quel est l'espacement idéal pour les plants de tomate ?",
      "Comment améliorer la fertilité du sol ?",
    ],
    welcomeMessage:
      "Je suis **Sesile**, votre assistante agronome. Posez-moi vos questions agricoles !",
    helpcenter: "SmartSaha – Centre d'aide",
    welcomehelp: "Bienvenue dans le guide SmartSaha",
    introhelp:
      "SmartSaha est une plateforme d’Agriculture de Précision conçue pour aider les agriculteurs à planifier, suivre et optimiser leurs cultures grâce à des données fiables et des analyses intelligentes.",
    learnmore: "En savoir plus sur",
    howitworks: "Comment fonctionne SmartSaha",
    step1title: "Inscription & Configuration",
    step1text:
      "Créez un compte et enregistrez vos parcelles pour recevoir des recommandations personnalisées.",
    step2title: "Collecte de données",
    step2text:
      "Les données météo, sol et cultures sont collectées via des capteurs, satellites et enquêtes terrain.",
    step3title: "Analyse intelligente",
    step3text:
      "Notre système analyse les données pour déterminer les besoins précis de chaque parcelle : irrigation, fertilisation et protection des cultures.",
    step4title: "Recommandations & Plan d’action",
    step4text:
      "Recevez des recommandations personnalisées avec un plan de travail détaillé pour chaque parcelle.",
    step5title: "Suivi & Optimisation",
    step5text:
      "Suivez l’évolution de vos cultures en temps réel et ajustez vos actions pour maximiser rendement et durabilité.",
    step6title: "Rapports & Décisions",
    step6text:
      "Obtenez des rapports complets pour prendre des décisions éclairées et améliorer la performance globale de votre exploitation.",
    needhelp: "Besoin d’aide supplémentaire ?",
    contactteam: "Contactez notre équipe de support :",
    location: "Antananarivo, Madagascar",
    cropStatusPlanned: "Planif.",
    cropStatusPlanted: "Plantée",
    cropStatusGerminated: "Germée",
    cropStatusGrowing: "Croiss.",
    cropStatusFlowering: "Flor.",
    cropStatusFruiting: "Fruits",
    cropStatusMature: "Mature",
    cropStatusHarvested: "Récoltée",
    cropStatusPostHarvest: "Post-récolte",
    cropStatusFailed: "Échouée",
    points: "Points ajoutés",
    nopoinntsfound: "Aucun point sélectionné sur la carte",
    policy: "Politique de Confidentialité",
    policyDate: "Dernière mise à jour : 30 septembre 2025",
    policy1Title: "1. Introduction",
    policy1Text:
      "SmartSaha s'engage à protéger votre vie privée et vos données personnelles. Cette politique explique comment nous collectons, utilisons, stockons et protégeons vos informations conformément à la législation malgache.",
    policy2Title: "2. Données Collectées",
    policy2Text: `
      <li><strong>Données d'identification :</strong> Nom, numéro de téléphone, e-mail, localisation de la ferme.</li>
      <li><strong>Données agricoles :</strong> Type de culture, superficie, historique des rendements, données du sol.</li>
      <li><strong>Données techniques :</strong> Identifiants de connexion, appareil, adresse IP, données de navigation.</li>
      <li><strong>Données géospatiales :</strong> Coordonnées GPS, images satellites.</li>
    `,
    policy3Title: "3. Utilisation de vos données",
    policy3Text: `
      <li>Fourniture des services et recommandations personnalisées.</li>
      <li>Optimisation de la plateforme et analyses.</li>
      <li>Notifications, alertes et communications agronomiques.</li>
      <li>Connexion avec des partenaires (avec votre consentement).</li>
      <li>Respect des obligations légales et réglementaires.</li>
    `,
    policy4Title: "4. Partage des données",
    policy4Text:
      "Nous ne vendons pas vos données. Le partage peut se faire avec des fournisseurs techniques, des partenaires de recherche anonymisés, les autorités légales ou des partenaires commerciaux uniquement avec votre consentement explicite.",
    policy5Title: "5. Sécurité des données",
    policy5Text:
      "Nous appliquons des mesures techniques et organisationnelles conformes aux standards du secteur pour garantir la protection des données.",
    policy6Title: "6. Vos droits",
    policy6Text:
      "Vous pouvez accéder, mettre à jour ou demander la suppression de vos données à tout moment. Contactez-nous à contact@smart-saha.com.",
    policy7Text: "SmartSaha, Antananarivo, Madagascar",
    terms: "Conditions d’Utilisation",
    termsDate: "Dernière mise à jour : 30 septembre 2025",
    terms1Title: "1. Préambule",
    terms1Text:
      "Ces Conditions d’Utilisation régissent l'utilisation de SmartSaha. L'accès ou l'utilisation de la plateforme implique l'acceptation totale de ces conditions.",
    terms2Title: "2. Description des services",
    terms2Text:
      "SmartSaha fournit des outils numériques aux agriculteurs, incluant des services d'agriculture de précision, des prévisions, des outils de gestion et un système MRV.",
    terms3Title: "3. Création de compte et responsabilité",
    terms3Text:
      "Les utilisateurs doivent fournir des informations exactes et garantir la confidentialité de leurs identifiants.",
    terms4Title: "4. Obligations de l'utilisateur",
    terms4Text: `
      <li>Utiliser la plateforme de manière responsable et légale.</li>
      <li>Fournir des informations agricoles exactes.</li>
      <li>S'abstenir d'activités frauduleuses ou illégales.</li>
    `,
    terms5Title: "5. Propriété intellectuelle",
    terms5Text:
      "SmartSaha possède tout le contenu de la plateforme. Les utilisateurs conservent la propriété de leurs données mais accordent à SmartSaha les droits nécessaires à la fourniture des services.",
    terms6Title: "6. Limitation de responsabilité",
    terms6Text:
      "Les recommandations sont uniquement des supports à la décision. SmartSaha n'est pas responsable des pertes agricoles. La responsabilité est limitée à une diligence raisonnable.",
    terms7Title: "7. Droit applicable",
    terms7Text:
      "Ces Conditions sont régies par la loi malgache. Les litiges relèvent des tribunaux d'Antananarivo, après tentative de résolution à l'amiable.",
    profileTitle: "Mon Profil",
    username: "Nom d'utilisateur",
    email: "Email",
    firstName: "Prénom",
    lastName: "Nom de famille",
    editProfile: "Modifier le Profil",
    account: "Compte",
    signOut: "Déconnexion",
    home: "Analyses",
    add: "Ajouter",
    changePasswordTitle: "Modifier le mot de passe",
    currentPassword: "Mot de passe actuel",
    newPassword: "Nouveau mot de passe",
    savePassword: "Enregistrer le mot de passe",
    passwordUpdated: "Mot de passe mis à jour avec succès",
    updateFailed: "Échec de la mise à jour",
    fillAllFields: "Veuillez remplir tous les champs",
    saveChanges: "Enregistrer",
    changePassword: "Modifier le mot de passe",
    sesily: "Salut! Je suis Sesily",
    prevision: "Prévision météo",
    today: "Aujourd'hui",
    humidity: "Humidité",
    pluie: "Pluie",
    vent: "Vent",
    forecastInfo: "Infos Météo",
    riskLevel: "Niveau de risque",
    locations: "Localisation",
    forecastPeriod: "Période de prévision",
    point: "Point",
    sun: "Dim",
    mon: "Lun",
    tue: "Mar",
    wed: "Mer",
    thu: "Jeu",
    fri: "Ven",
    sat: "Sam",

    january: "Janvier",
    february: "Février",
    march: "Mars",
    april: "Avril",
    may: "Mai",
    june: "Juin",
    july: "Juillet",
    august: "Août",
    september: "Septembre",
    october: "Octobre",
    november: "Novembre",
    december: "Décembre",

    tasks_for: "Tâches du",

    weekday_0: "Dimanche",
    weekday_1: "Lundi",
    weekday_2: "Mardi",
    weekday_3: "Mercredi",
    weekday_4: "Jeudi",
    weekday_5: "Vendredi",
    weekday_6: "Samedi",

    month_0: "Janvier",
    month_1: "Février",
    month_2: "Mars",
    month_3: "Avril",
    month_4: "Mai",
    month_5: "Juin",
    month_6: "Juillet",
    month_7: "Août",
    month_8: "Septembre",
    month_9: "Octobre",
    month_10: "Novembre",
    month_11: "Décembre",
    totalTask: "Total des tâches",
    taskByPriority: "Tâches par priorité",
    taskProgression: "Progression des tâches",
    deleteParcel: "Supprimer la parcelle",
    textConfirmDeleteParcel:
      "Êtes-vous sûr de vouloir supprimer cette parcelle ? Cette action est irréversible.",
    yes: "Oui",
    no: "Non",
    precipitation: "Précipitations",
    uvIndex: "Indice UV",
    pointsParcel: "Points de la parcelle",
    markDone: "Marquer comme terminée",
    analyseMeteo: "Analyse Agricole et Météo",
    temp: "Température",
    alertAgricole: "Alerte Agricole",
    irrigationRecommander: "Recommandation d'irrigation",
    analyseRisk: "Analyse des risques",
    condition: "Condition actuelle",
    resetMdpTittle: "Réinitialiser le mot de passe",
    resetText:
      "Entrez l'adresse e-mail liée à votre compte. Nous vous enverrons un lien pour créer un nouveau mot de passe.",
    resetEmail: "Adresse e-mail",
    resetBtn: "Envoyer le lien de réinitialisation",
    resetLabel: "Veuillez saisir une adresse e-mail valide.",
    errorMessage: "Lien envoyé, vérifiez votre boîte e-mail",
    return: "Retour à la connexion",
    responseMessage:
      "Si l'email existe dans notre système, vous recevrez un message contenant un lien de réinitialisation. Le lien peut prendre quelques minutes pour arriver.",
    skip: "Passer",
    step: "Étape",
    stepTittle: "Assistant de configuration",
    allParcel: "Toutes les parcelles",
    exportChart: "Exporter le graphique",
    cumulativeYield: "Rendement cumulé",
    volatility: "Volatilité (Écart-type)",
    yieldRelative: "Rendement relatif %",
    anomalies: "Anomalies détectées",
    selectParcel: "Sélectionner une parcelle",
    fertility: "Sol le plus fertile",
    productivity: "Culture la plus productive",
    total: "Total",
    tempAverage: "Température moyenne",
    riskParcel: "Parcelle à risque",
    alerts: "Alertes",
    bestRendement: "Meilleur rendement",
    moyenne: "Moyenne",
    cultureSansDonnees: "Cultures sans données",
    culture: "cultures",
  },
  mg: {
    dashboard: "Tabilao",
    parcels: "Tany",
    tasks: "Asa",
    yields: "Vokatra",
    crops: "Zavamaniry",
    help: "Fanampiana",
    logout: "Hivoaka",
    slogan: "Angona nokarakaraina, vokatra nojinjaina",
    activeparcels: "Tany miasa",
    completedtasks: "Asa vita",
    totalyield: "Vokatra totaly",
    averageyield: "Vokatra antonony",
    zoomonparcel: "Ahodina ny Tany",
    search: "Mitadiava tany...",
    titleanalytics: "Famakafakana",
    charttitleyield: "Fivoaran’ny vokatra",
    parcelanalytics: "Famakafakana Tany",
    parcel: "Tany",
    sortby: "Filaharana araka",
    sortname: "Anarana (A → Z)",
    sortyield: "Vokatra (midina)",
    meanyield: "Vokatra antonony",
    meanyieldperarea: "Vokatra antonony isaky ny faritra",
    yieldperarea: "Vokatra isaky ny faritra",
    titleparcellist: "Lisitry ny Tany",
    rowperpage: "Laharana isaky ny pejy:",
    filterbyowner: "Sivana araka ny tompony",
    filterbyparcel: "Sivana araka ny tany",
    export: "Aondrana",
    addparcel: "Ampio Tany",
    thparcelname: "Tany",
    thlatitude: "Zanabola",
    thlongitude: "Lavabola",
    thactions: "Hetsika",
    prev: "Taloha",
    next: "Manaraka",
    noparcelsfound: "Tsy misy Tany hita.",
    instructions: "Torolàlana",
    step1:
      "Voalohany, ampiasao ny <span class='font-semibold'>baran’ny fitadiavana</span> hahitana ny taninao.",
    step2:
      "Tsindrio ny <span class='font-semibold'>sarintany</span> mba hanampy teboka sy hanaovana ny taninao.",
    step3:
      "Ilaina farafahakeliny <span class='font-semibold'>teboka 3</span> mba hamoronana polygona.",
    step4:
      "Ampidiro ny <span class='font-semibold'>anarana ny Tany</span> ao amin’ny endrika.",
    step5:
      "Farany, tsindrio ny <span class='font-semibold text-[#f4a261]'>Tehirizo ny Tany</span> mba hanamarina.",
    titlesaveparcel: "Tehirizo ny Tany",
    searchintruction: "Tsindrio ny sarintany mba hanaovana polygona.",
    searchonmap: "Mitadiava eo amin’ny sarintany",
    parcelarea: "Faritra Tany",
    btnsaveparcel: "Tehirizo ny Tany",
    parceldetail: "Antsipirian’ny Tany",
    owner: "Tompony",
    area: "Faritra",
    croptype: "Karazana Zavamaniry",
    charttitleweather: "Toetr’andro",
    chartprecipitation: "Orana",
    soilinfo: "Momba ny Tany",
    titletaskperform: "Asa tokony hatao",
    seeall: "Jereo rehetra",
    addtask: "Ampio Asa",
    charttitletask: "Fivoaran’ny asa",
    harvesthistory: "Tantara Fivokarana",
    thdate: "Daty",
    thyield: "Vokatra (kg)",
    thobservation: "Fanamarihana",
    thtendance: "Fironana",
    edit: "Hanova",
    show: "Haneho",
    nohistoryfound: "Tsy misy rakitra hita.",
    priorityLow: "Ambany",
    priorityMedium: "Antonony",
    priorityHigh: "Ambony",
    priority: "Lainga",
    due: "Voatondro",
    statusPending: "Miandry",
    statusInProgress: "Eo am-panatanterahana",
    statusDone: "Vita",
    statusCancelled: "Nanafoana",
    chartTasksByStatus: "Asa araka ny sata",
    chartYieldEvolution: "Vokatra (kg)",
    chartTemperature: "Mari-pana (°C)",
    chartPrecipitation: "Orana (mm/andro)",
    titleeditparcel: "Hanova Tany",
    titiletaskslist: "Lisitry ny Asa",
    history: "Tantara",
    upcoming: "Hatreto ho avy",
    btnaddtask: "Ampio Asa",
    taskname: "Asa",
    parcelcrop: "Zavamaniry ao amin’ny Tany",
    status: "Sata",
    notaskfound: "Tsy misy asa hita.",
    titlenewtask: "Asa vaovao",
    desc: "Famaritana",
    detailtask: "Antsipirian’ny Asa",
    createdat: "Noforonina tamin’ny",
    updatedat: "Nohavaozina tamin’ny",
    completedat: "Vita tamin’ny",
    back: "Miverina",
    edittask: "Hanova Asa",
    savetask: "Tehirizo Asa",
    yieldlist: "Rakitra vokatra",
    btnyield: "Ampio vokatra",
    crop: "Zavamaniry",
    noyieldfound: "Tsy misy rakitra vokatra hita.",
    newyield: "Vokatra vaovao",
    notes: "Fanamarihana",
    yielddetail: "Antsipirian’ny vokatra",
    edityield: "Hanova vokatra",
    btnsaveyield: "Tehirizo vokatra",
    parcelcroplist: "Lisitry ny Zavamaniry ao amin’ny Tany",
    btnaddparcelcrop: "Ampio Zavamaniry",
    plantingdate: "Daty Fambolena",
    harvestdate: "Daty Fivokarana",
    noparcelcropfound: "Tsy misy zavamaniry hita ao amin’ny tany.",
    newparcelcrop: "Zavamaniry vaovao",
    btnaddcrop: "Ampio Zavamaniry",
    btnsaveparcelcrop: "Tehirizo Zavamaniry",
    titleyieldforcast: "Vinavinan’ny vokatra",
    forecastdate: "Daty Vinavina",
    pareclcropdetail: "Antsipirian’ny Zavamaniry ao amin’ny Tany",
    editparcelcrop: "Hanova Zavamaniry ao amin’ny Tany",
    newcrop: "Zavamaniry vaovao",
    cropname: "Anaran’ny Zavamaniry",
    variety: "Karazana",
    btnsavecrop: "Tehirizo Zavamaniry",
    heroTitle:
      "Izaho dia Sesily, Mpiasan’ny Agronomista anao. <br/>Anontanio ny fanontaniana momba ny fambolena!",
    ask: "Manontania fanontaniana",
    suggestedQuestions: [
      "Inona ny zezika tsara indrindra ho an’ny vary?",
      "Ahoana ny hisorohana ny bibikely amin’ny katsaka?",
      "Rahoviana no tokony hambolena cassava?",
      "Inona ny elanelana mety ho an’ny voatabia?",
      "Ahoana ny hanatsarana ny fambolena sy ny tany?",
    ],
    welcomeMessage:
      "Izaho dia **Sesile**, Mpiasan’ny Agronomista anao. Anontanio ny fanontanianao momba ny fambolena!",
    helpcenter: "SmartSaha – Foiben’ny fanampiana",
    welcomehelp: "Tongasoa eto amin’ny Torolàlana SmartSaha",
    introhelp:
      "SmartSaha dia sehatra Fambolena Marina natao hanampiana ny tantsaha handamina, hanara-maso, ary hanatsara ny vokatra mampiasa angona azo antoka sy famakafakana marani-tsaina.",
    learnmore: "Hianara bebe kokoa ao amin’ny",
    howitworks: "Ahoana ny fiasan’ny SmartSaha",
    step1title: "Hisoratra anarana & Fikirakirana",
    step1text:
      "Mamoròna kaonty ary manorata ny tanim-pambolenao mba hahazoana torohevitra manokana.",
    step2title: "Fangonam-baovao",
    step2text:
      "Angonina ny toetr’andro, ny tany, ary ny vokatra amin’ny alalan’ny sensors, satellites, ary fanadihadiana eny an-tsaha.",
    step3title: "Famakafakana marani-tsaina",
    step3text:
      "Analizina ny angona mba hamantarana ny filàna marina isaky ny tany: famafazana rano, zezika, ary fiarovana ny zavamaniry.",
    step4title: "Torohevitra & Drafitra Asa",
    step4text:
      "Hahazo torohevitra manokana miaraka amin’ny drafitra asa ho an’ny tany tsirairay.",
    step5title: "Fanaraha-maso & Fanatsarana",
    step5text:
      "Araho ny fivoaran’ny vokatra amin’ny fotoana tena izy ary amboary ny hetsika hahazoana vokatra ambony sy maharitra.",
    step6title: "Tatitra & Fandraisana fanapahan-kevitra",
    step6text:
      "Mahazoa tatitra feno mba handraisana fanapahan-kevitra tsara sy hanatsarana ny fahombiazan’ny fambolena amin’ny ankapobeny.",
    needhelp: "Mila fanampiana fanampiny?",
    contactteam: "Mifandraisa amin’ny ekipa mpanohana:",
    location: "Antananarivo, Madagasikara",
    cropStatusPlanned: "Voaomana",
    cropStatusPlanted: "Nambolena",
    cropStatusGerminated: "Voavokatra",
    cropStatusGrowing: "Mitombo",
    cropStatusFlowering: "Miketrika",
    cropStatusFruiting: "Mihamero",
    cropStatusMature: "Matanjaka",
    cropStatusHarvested: "Voavokatra",
    cropStatusPostHarvest: "Taorian’ny Fivokarana",
    cropStatusFailed: "Tsy Vokatra",
    points: "Teboka nampiana",
    nopoinntsfound: "Tsy misy teboka voafidy eo amin’ny sarintany",
    policy: "Politika momba ny tsiambaratelo",
    policyDate: "Nohavaozina farany: 30 Septambra 2025",
    policy1Title: "1. Fampidirana",
    policy1Text:
      "Ny SmartSaha dia manolo-tena amin'ny fiarovana ny tsiambaratelonao sy ny angon-drakitrao manokana. Ity politika ity dia manazava ny fomba fakàna, fampiasana, fitahirizana, sy fiarovana ny vaovao mifanaraka amin'ny lalàna Malagasy.",
    policy2Title: "2. Angon-drakitra Fakàna",
    policy2Text: `
      <li><strong>Angon-drakitra mombam-pahafantarana :</strong> Anarana, laharana finday, mailaka, toerana fambolena.</li>
      <li><strong>Angon-drakitra fambolena :</strong> Karazan-tsakafo, haben'ny tany, tantaran'ny vokatra, angon-drakitra tany.</li>
      <li><strong>Angon-drakitra teknika :</strong> Mombam-pidirana, fitaovana, adiresy IP, angon-drakitra fitsidihana.</li>
      <li><strong>Angon-drakitra ara-jeografika :</strong> Kaody GPS, sary avy amin'ny zanabolana.</li>
    `,
    policy3Title: "3. Fampiasana ny angon-drakitrao",
    policy3Text: `
      <li>Fanomezana serivisy sy soso-kevitra manokana.</li>
      <li>Fanatsarana ny sehatra sy fanadihadiana.</li>
      <li>Fampandrenesana, fanairana, ary fifandraisana amin'ny agronomia.</li>
      <li>Fifandraisana amin'ny mpiara-miombon'antoka (amin'ny fankatoavanao).</li>
      <li>Fanaraha-maso ny lalàna sy fitsipika.</li>
    `,
    policy4Title: "4. Fizarana angon-drakitra",
    policy4Text:
      "Tsy amidinay ny angon-drakitrao. Mety hizara amin'ny mpamatsy teknika, mpiara-miasa amin'ny fikarohana tsy misy anarana, manampahefana ara-dalàna, na mpiara-miombon'antoka ara-barotra amin'ny fankatoavanao mazava ihany.",
    policy5Title: "5. Fiarovana ny angon-drakitra",
    policy5Text:
      "Mampihatra fepetra teknika sy fikarakarana araka ny fenitra iraisam-pirenena izahay mba hiantohana ny fiarovana ny angon-drakitra.",
    policy6Title: "6. Zo azonao",
    policy6Text:
      "Azonao atao ny miditra, manavao, na mangataka famafana ny angon-drakitrao amin'ny fotoana rehetra. Mifandraisa aminay: contact@smart-saha.com.",
    policy7Text: "SmartSaha, Antananarivo, Madagascar",
    terms: "Fepetra sy fitsipika amin’ny fampiasana",
    termsDate: "Nohavaozina farany: 30 Septambra 2025",
    terms1Title: "1. Fanambarana",
    terms1Text:
      "Ireto Fepetra ireto dia mifehy ny fampiasana ny SmartSaha. Ny fidirana na fampiasana ny sehatra dia midika fankatoavana tanteraka ireo fepetra ireo.",
    terms2Title: "2. Famaritana ny Serivisy",
    terms2Text:
      "SmartSaha dia manome fitaovana nomerika ho an'ny mpamboly, anisan'izany ny serivisy fambolena marina, vinavina, fitaovana fitantanana, ary rafitra MRV.",
    terms3Title: "3. Famoronana kaonty & andraikitra",
    terms3Text:
      "Ny mpampiasa dia tsy maintsy manome vaovao marina ary miaro ny tsiambaratelon'ny kaontiny.",
    terms4Title: "4. Adidin'ny mpampiasa",
    terms4Text: `
      <li>Mampiasa ny sehatra amin'ny fomba tompon'andraikitra sy ara-dalàna.</li>
      <li>Mampiditra vaovao fambolena marina.</li>
      <li>Misoroka asa sandoka na tsy ara-dalàna.</li>
    `,
    terms5Title: "5. Zon'ny fananana ara-tsaina",
    terms5Text:
      "Ny SmartSaha no tompon'ny votoaty rehetra ao amin'ny sehatra. Ny mpampiasa dia mitazona ny angon-drakitr’izy ireo fa manome alalana ny SmartSaha hampiasa izany ilaina amin'ny fanomezana serivisy.",
    terms6Title: "6. Fetra amin'ny andraikitra",
    terms6Text:
      "Ny soso-kevitra dia fanohanana fanapahan-kevitra fotsiny. Tsy tompon’andraikitra amin’ny fahaverezan’ny vokatra ny SmartSaha. Ny andraikitra dia voafetra amin'ny fahamailoana antonony.",
    terms7Title: "7. Lalàna mifehy",
    terms7Text:
      "Ireo Fepetra ireo dia fehezin'ny lalàna Malagasy. Ny fifandirana dia eo ambany fahefan'ny fitsarana Antananarivo, aorian'ny ezaka hamahana ny olana am-pilaminana.",
    username: "Anaran'ny mpampiasa",
    email: "Mailaka",
    firstName: "Anarana",
    lastName: "Fanampiny",
    editProfile: "Hanova ny mombam-piainana",
    account: "Kaonty",
    signOut: "Hivoaka",
    home: "Famakafakana",
    add: "Ampio",
    profileTitle: "Mombamomba",
    changePasswordTitle: "Hanova tenimiafina",
    currentPassword: "Tenimiafina ankehitriny",
    newPassword: "Tenimiafina vaovao",
    savePassword: "Tehirizo ny tenimiafina",
    passwordUpdated: "Vaovao ny tenimiafina",
    updateFailed: "Tsy nahomby ny fanavaozana",
    fillAllFields: "Fenoy daholo ny saha rehetra",
    saveChanges: "Tehirizo ny fanovana",
    changePassword: "Hanova ny tenimiafina",
    sesily: "Salama! Izaho i Sesily",
    prevision: "Vinavinan'ny toetr'andro",
    today: "Anio",
    humidity: "Hamandoana",
    pluie: "Orana",
    vent: "Rivotra",
    forecastInfo: "Fampahafantarana ny Toetr’andro",
    riskLevel: "Haavo loza",
    locations: "Toerana",
    forecastPeriod: "Fotoana vinavina",
    point: "teboka",
    sun: "Alah",
    mon: "Alats",
    tue: "Tal",
    wed: "Alar",
    thu: "Alak",
    fri: "Zom",
    sat: "Sab",

    january: "Janoary",
    february: "Febroary",
    march: "Martsa",
    april: "Aprily",
    may: "Mey",
    june: "Jona",
    july: "Jolay",
    august: "Aogositra",
    september: "Septambra",
    october: "Oktobra",
    november: "Novambra",
    december: "Desambra",

    tasks_for: "Asa ho an’ny",
    weekday_0: "Alahady",
    weekday_1: "Alatsinainy",
    weekday_2: "Talata",
    weekday_3: "Alarobia",
    weekday_4: "Alakamisy",
    weekday_5: "Zoma",
    weekday_6: "Sabotsy",

    month_0: "Janoary",
    month_1: "Febroary",
    month_2: "Martsa",
    month_3: "Aprily",
    month_4: "Mey",
    month_5: "Jona",
    month_6: "Jolay",
    month_7: "Aogositra",
    month_8: "Septambra",
    month_9: "Oktobra",
    month_10: "Novambra",
    month_11: "Desambra",
    totalTask: "Asa totaly",
    taskByPriority: "Asa araka ny lainga",
    taskProgression: "Fandrosoan'ny asa",
    deleteParcel: "Fafao ny Tany",
    textConfirmDeleteParcel:
      "Azonao antoka ve fa hamafa ity tany ity ianao? Tsy azo averina ity hetsika ity.",
    yes: "Eny",
    no: "Tsia",
    precipitation: "Rano avy amin'ny orana",
    uvIndex: "Isa UV",
    pointsParcel: "Teboky ny tany",
    markDone: "Mariho ho vita",
    analyseMeteo: "Famakafakana ara-pambolena sy toetr'andro",
    temp: "Mari-pana",
    alertAgricole: "Fanairana ara-pambolena",
    irrigationRecommander: "Soso-kevitra famafazana rano",
    analyseRisk: "Famakafakana loza",
    condition: "Toe-javatra ankehitriny",
    resetMdpTittle: "Avereno ny tenimiafina",
    resetText:
      "Ampidiro ny adiresy mailaka mifandray amin'ny kaontinao. Handefa rohy hamoronana tenimiafina vaovao izahay.",
    resetEmail: "Adiresy mailaka",
    resetBtn: "Alefaso ny rohy fanarenana",
    resetLabel: "Azafady, ampidiro adiresy mailaka mety.",
    errorMessage: "Rohy nalefa, jereo ny boaty mailakao",
    return: "Miverina amin'ny fidirana",
    responseMessage:
      "Raha misy ny mailaka ao amin'ny rafitrao, dia hahazo hafatra misy rohy fanarenana ianao. Mety haharitra minitra vitsivitsy vao tonga ny rohy.",
    skip: "Tsindrio",
    step: "Dingana",
    stepTittle: "Mpitarika fikirakirana",
    allParcel: "Tany rehetra",
    exportChart: "Aondrana ny tabilao",
    cumulativeYield: "Vokatra mitambatra",
    volatility: "Fiovaovana (Fanoloran-tena)",
    yieldRelative: "Vokatra mifandraika %",
    anomalies: "Fahadisoana hita",
    selectParcel: "Misafidiana Tany",
    fertility: "Tany be zezika indrindra",
    productivity: "Fambolena be vokatra indrindra",
    total: "Totaly",
    tempAverage: "Maripana antonony",
    riskParcel: "Tany mety ho loza",
    alerts: "Fampitandremana",
    bestRendement: "Vokatra tsara indrindra",
    moyenne: "Salan'isa",
    cultureSansDonnees: "Fambolena tsy misy angona",
    culture: "fambolena",
  },
};
