export const translate = {
  en: {
    dashboard: "Dashboard",
    parcels: "Parcels",
    tasks: "Tasks",
    yields: "Yields",
    crops: "Crops",
    help: "Help",
    logout: "Logout",
    slogan: "Nurture data. Harvest impact",
    activeparcels: "Active parcels",
    completedtasks: "Completed tasks",
    totalyield: "Total yield",
    averageyield: "Average yield",
    zoomonparcel: "Zoom on Parcel",
    search: "Search on parcel...",
    titleanalytics: "Analytics",
    charttitleyield: "Yield Evolution",
    parcelanalytics: "Parcels Analytics",
    parcel: "Parcel",
    sortby: "Sort by",
    sortname: "Name (A → Z)",
    sortyield: "Yield (desc)",
    meanyield: "Mean Yield",
    meanyieldperarea: "Mean Yield per Area",
    yieldperarea: "Yield per Area",
    titleparcellist: "Parcels List",
    rowperpage: "Rows per page:",
    filterbyowner: "Filter by Owner",
    filterbyparcel: "Filter by Parcel",
    export: "Export",
    addparcel: "Add Parcel",
    thparcelname: "Parcel",
    thlatitude: "Latitude",
    thlongitude: "Longitude",
    thactions: "Actions",
    prev: "Prev",
    next: "Next",
    noparcelsfound: "No Parcels found.",
    instructions: "Instructions",
    step1:
      "First, use the <span class='font-semibold'>search bar</span> to locate your field.",
    step2:
      "Click on the <span class='font-semibold'>map</span> to add points and draw your parcel.",
    step3:
      "A minimum of <span class='font-semibold'>3 points</span> is required to create a polygon.",
    step4:
      "Enter a <span class='font-semibold'>parcel name</span> in the form.",
    step5:
      "Finally, click <span class='font-semibold text-[#f4a261]'>Save parcel</span> to validate.",
    titlesaveparcel: "Save Parcel",
    searchintruction: "Click on the map to draw your polygon.",
    searchonmap: "Search on map",
    parcelarea: "Parcel Area",
    btnsaveparcel: "Save parcel",
    parceldetail: "Parcel Details",
    owner: "Owner",
    area: "Area",
    croptype: "Crop Type",
    charttitleweather: "Weather Condition",
    chartprecipitation: "Precipitation",
    soilinfo: "Soil Info",
    titletaskperform: "Tasks to Perform",
    seeall: "See All",
    addtask: "Add Task",
    charttitletask: "Tasks evolution",
    harvesthistory: "Harvest History",
    thdate: "Date",
    thyield: "Yield (kg)",
    thobservation: "Observation",
    thtendance: "Trend",
    edit: "Edit",
    show: "Show",
    nohistoryfound: "No records found.",
    priorityLow: "Low",
    priorityMedium: "Medium",
    priorityHigh: "High",
    priority: "Priority",
    due: "Due",
    statusPending: "Pending",
    statusInProgress: "In Progress",
    statusDone: "Done",
    statusCancelled: "Cancelled",
    chartTasksByStatus: "Tasks by Status",
    chartYieldEvolution: "Yield (kg)",
    chartTemperature: "Temperature (°C)",
    chartPrecipitation: "Precipitation (mm/day)",
    titleeditparcel: "Edit parcel",
    titiletaskslist: "Tasks List",
    history: "History",
    upcoming: "Upcoming",
    btnaddtask: "Add task",
    taskname: "Task",
    parcelcrop: "Parcel Crop",
    status: "Status",
    notaskfound: "No tasks found.",
    titlenewtask: "New task",
    desc: "Description",
    detailtask: "Task Details",
    createdat: "Created At",
    updatedat: "Updated At",
    completedat: "Completed At",
    back: "Back",
    edittask: "Edit Task",
    savetask: "Save Task",
    yieldlist: "Yield Records",
    btnyield: "Add Yield",
    crop: "Crop",
    noyieldfound: "No yield records found.",
    newyield: "New Yield",
    notes: "Notes",
    yielddetail: "Yield Detail",
    edityield: "Edit Yield",
    btnsaveyield: "Save Yield",
    parcelcroplist: "Parcel Crops List",
    btnaddparcelcrop: "Add Parcel Crop",
    plantingdate: "Planting Date",
    harvestdate: "Harvest Date",
    noparcelcropfound: "No parcel crops found.",
    newparcelcrop: "New Parcel Crop",
    btnaddcrop: "Add Crop",
    btnsaveparcelcrop: "Save Parcel Crop",
    titleyieldforcast: "Yield Forecast",
    forecastdate: "Forecast Date",
    pareclcropdetail: "Parcel Crop Details",
    editparcelcrop: "Edit Parcel Crop",
    newcrop: "New crop",
    cropname: "Crop Name",
    variety: "Variety",
    btnsavecrop: "Save Crop",
    heroTitle:
      "I'm Sesily, your Agronomist Assistant. <br/>Ask me your farming questions!",
    ask: "Ask a question",
    suggestedQuestions: [
      "What is the best fertilizer for rice?",
      "How do I prevent maize pests?",
      "When should I plant cassava?",
      "What is the right spacing for tomato plants?",
      "How can I improve soil fertility?",
    ],
    welcomeMessage:
      "I’m **Sesile**, your Agronomist Assistant. Ask me your farming questions!",
    helpcenter: "SmartSaha – Help Center",
    welcomehelp: "Welcome to SmartSaha Guide",
    introhelp:
      "SmartSaha is a Precision Agriculture platform designed to help farmers plan, monitor, and optimize their crops using reliable data and intelligent analytics.",
    learnmore: "Learn more at",
    howitworks: "How SmartSaha Works",
    step1title: "Sign Up & Setup",
    step1text:
      "Create an account and register your farm plots to start receiving personalized recommendations.",
    step2title: "Data Collection",
    step2text:
      "Weather, soil, and crop data are collected through sensors, satellites, and field surveys.",
    step3title: "Smart Analysis",
    step3text:
      "Our system analyzes the data to determine the precise needs of each plot: irrigation, fertilization, and crop protection.",
    step4title: "Recommendations & Action Plan",
    step4text:
      "Receive tailored recommendations along with a detailed work plan for each plot.",
    step5title: "Monitoring & Optimization",
    step5text:
      "Track crop progress in real time and adjust actions to maximize yield and sustainability.",
    step6title: "Reports & Decision Making",
    step6text:
      "Get comprehensive reports to make informed decisions and improve overall farm performance.",
    needhelp: "Need Further Assistance?",
    contactteam: "Reach out to our support team:",
    location: "Antananarivo, Madagascar",
    cropStatusPlanned: "Planned",
    cropStatusPlanted: "Planted",
    cropStatusGerminated: "Germinated",
    cropStatusGrowing: "Growing",
    cropStatusFlowering: "Flowering",
    cropStatusFruiting: "Fruiting",
    cropStatusMature: "Mature",
    cropStatusHarvested: "Harvested",
    cropStatusPostHarvest: "Post-Harvest",
    cropStatusFailed: "Failed",
    points: "Added Points",
    nopoinntsfound: "No points selected on the map",

  },
  fr: {
    dashboard: "Tableau",
    parcels: "Parcelles",
    tasks: "Tâches",
    yields: "Rendements",
    crops: "Cultures",
    help: "Aide",
    logout: "Quitter",
    slogan: "Données nourries. Impact récolté",
    activeparcels: "Parcelles actives",
    completedtasks: "Tâches Terminées",
    totalyield: "Total Rendements",
    averageyield: "Moyenne",
    zoomonparcel: "Zoom parcelle",
    search: "Rechercher...",
    titleanalytics: "Analyse",
    charttitleyield: "Évolution",
    parcelanalytics: "Analyse parcelles",
    parcel: "Parcelle",
    sortby: "Trier",
    sortname: "Nom (A → Z)",
    sortyield: "Rendement ↓",
    meanyield: "Moyenne",
    meanyieldperarea: "Moyenne/Surface",
    yieldperarea: "Rend./Surface",
    titleparcellist: "Parcelles",
    rowperpage: "Lignes/page :",
    filterbyowner: "Par propriétaire",
    filterbyparcel: "Par parcelle",
    export: "Exporter",
    addparcel: "Ajouter",
    thparcelname: "Parcelle",
    thlatitude: "Latitude",
    thlongitude: "Longitude",
    thactions: "Actions",
    prev: "Préc.",
    next: "Suiv.",
    noparcelsfound: "Aucune parcelle",
    instructions: "Instructions",
    step1:
      "D’abord, utilisez la <span class='font-semibold'>barre de recherche</span> pour localiser votre champ.",
    step2:
      "Cliquez sur la <span class='font-semibold'>carte</span> pour ajouter des points et tracer votre parcelle.",
    step3:
      "Un minimum de <span class='font-semibold'>3 points</span> est requis pour créer un polygone.",
    step4:
      "Saisissez un <span class='font-semibold'>nom de parcelle</span> dans le formulaire.",
    step5:
      "Enfin, cliquez sur <span class='font-semibold text-[#f4a261]'>Enregistrer la parcelle</span> pour valider.",
    titlesaveparcel: "Enregistrer la parcelle",
    searchintruction: "Cliquez sur la carte pour tracer votre polygone.",
    searchonmap: "Rechercher sur la carte",
    parcelarea: "Surface de la parcelle",
    btnsaveparcel: "Enregistrer la parcelle",
    parceldetail: "Détails Parcelle",
    owner: "Propriétaire",
    area: "Surface",
    croptype: "Type de culture",
    charttitleweather: "Conditions météo",
    chartprecipitation: "Précipitations",
    soilinfo: "Infos sol",
    titletaskperform: "Tâches à effectuer",
    seeall: "Tout voir",
    addtask: "Ajouter tâche",
    charttitletask: "Évolution des tâches",
    harvesthistory: "Historique récoltes",
    thdate: "Date",
    thyield: "Rendement (kg)",
    thobservation: "Observation",
    thtendance: "Tendance",
    edit: "Modifier",
    show: "Voir",
    nohistoryfound: "Aucun enregistrement",
    priorityLow: "Faible",
    priorityMedium: "Moyenne",
    priorityHigh: "Haute",
    priority: "Priorité",
    due: "Échéance",
    statusPending: "En attente",
    statusInProgress: "En cours",
    statusDone: "Terminée",
    statusCancelled: "Annulée",
    chartTasksByStatus: "Tâches par statut",
    chartYieldEvolution: "Rendement (kg)",
    chartTemperature: "Température (°C)",
    chartPrecipitation: "Précipitations (mm/jour)",
    titleeditparcel: "Modifier la parcelle",
    titiletaskslist: "Liste des tâches",
    history: "Historique",
    upcoming: "À venir",
    btnaddtask: "Ajouter tâche",
    taskname: "Tâche",
    parcelcrop: "Culture parcelle",
    status: "Statut",
    notaskfound: "Aucune tâche trouvée",
    titlenewtask: "Nouvelle tâche",
    desc: "Description",
    detailtask: "Détails de la tâche",
    createdat: "Créée le",
    updatedat: "Mise à jour le",
    completedat: "Terminée le",
    back: "Retour",
    edittask: "Modifier la tâche",
    savetask: "Enregistrer la tâche",
    yieldlist: "Rendements",
    btnyield: "Ajouter rendement",
    crop: "Culture",
    noyieldfound: "Aucun rendement trouvé",
    newyield: "Nouveau rendement",
    notes: "Notes",
    yielddetail: "Détails du rendement",
    edityield: "Modifier le rendement",
    btnsaveyield: "Enregistrer rendement",
    parcelcroplist: "Cultures de la parcelle",
    btnaddparcelcrop: "Ajouter culture",
    plantingdate: "Date de plantation",
    harvestdate: "Date de récolte",
    noparcelcropfound: "Aucune culture trouvée",
    newparcelcrop: "Nouvelle culture",
    btnaddcrop: "Ajouter culture",
    btnsaveparcelcrop: "Enregistrer culture",
    titleyieldforcast: "Prévision de rendement",
    forecastdate: "Date de prévision",
    pareclcropdetail: "Détails culture parcelle",
    editparcelcrop: "Modifier culture",
    newcrop: "Nouvelle culture",
    cropname: "Nom de la culture",
    variety: "Variété",
    btnsavecrop: "Enregistrer culture",
    heroTitle:
      "Je suis Sesily, votre assistante agronome. <br/>Posez-moi vos questions agricoles !",
    ask: "Poser une question",
    suggestedQuestions: [
      "Quel est le meilleur engrais pour le riz ?",
      "Comment prévenir les ravageurs du maïs ?",
      "Quand faut-il planter le manioc ?",
      "Quel est l'espacement idéal pour les plants de tomate ?",
      "Comment améliorer la fertilité du sol ?",
    ],
    welcomeMessage:
      "Je suis **Sesile**, votre assistante agronome. Posez-moi vos questions agricoles !",
    helpcenter: "SmartSaha – Centre d'aide",
    welcomehelp: "Bienvenue dans le guide SmartSaha",
    introhelp:
      "SmartSaha est une plateforme d’Agriculture de Précision conçue pour aider les agriculteurs à planifier, suivre et optimiser leurs cultures grâce à des données fiables et des analyses intelligentes.",
    learnmore: "En savoir plus sur",
    howitworks: "Comment fonctionne SmartSaha",
    step1title: "Inscription & Configuration",
    step1text:
      "Créez un compte et enregistrez vos parcelles pour recevoir des recommandations personnalisées.",
    step2title: "Collecte de données",
    step2text:
      "Les données météo, sol et cultures sont collectées via des capteurs, satellites et enquêtes terrain.",
    step3title: "Analyse intelligente",
    step3text:
      "Notre système analyse les données pour déterminer les besoins précis de chaque parcelle : irrigation, fertilisation et protection des cultures.",
    step4title: "Recommandations & Plan d’action",
    step4text:
      "Recevez des recommandations personnalisées avec un plan de travail détaillé pour chaque parcelle.",
    step5title: "Suivi & Optimisation",
    step5text:
      "Suivez l’évolution de vos cultures en temps réel et ajustez vos actions pour maximiser rendement et durabilité.",
    step6title: "Rapports & Décisions",
    step6text:
      "Obtenez des rapports complets pour prendre des décisions éclairées et améliorer la performance globale de votre exploitation.",
    needhelp: "Besoin d’aide supplémentaire ?",
    contactteam: "Contactez notre équipe de support :",
    location: "Antananarivo, Madagascar",
    cropStatusPlanned: "Planif.",
    cropStatusPlanted: "Plantée",
    cropStatusGerminated: "Germée",
    cropStatusGrowing: "Croiss.",
    cropStatusFlowering: "Flor.",
    cropStatusFruiting: "Fruits",
    cropStatusMature: "Mature",
    cropStatusHarvested: "Récoltée",
    cropStatusPostHarvest: "Post-récolte",
    cropStatusFailed: "Échouée",
    points: "Points ajoutés",
    nopoinntsfound: "Aucun point sélectionné sur la carte",
  },
};
